name: MODDY DEV CI

on:
  push:
    branches: [ "develop" ]
  pull_request: 
    branches: [ "develop" ]

jobs:
  build: 
    runs-on: ubuntu-22.04 
    env:
      working-directory: moddy-server

    steps:
    - name: 체크아웃
      uses: actions/checkout@v3

    - name: Set up JDK 17 
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        character set server: 'utf8'
        mysql database: 'moddy'
        mysql user: 'moddy'
        mysql password: ${{ secrets.DatabasePassword }}

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: 6

    - name: application.yml 생성
      run: | 
          cd src/main/resources 
          echo "${{ secrets.APPLICATION }}" > ./application.yml

    - name: 빌드
      run: |
          chmod +x gradlew
          ./gradlew build -x test
      shell: bash
