name: MODDY DEV CD

on:
  push:
    branches: [ "feat/#207" ]

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04
    env:
      working-directory: moddy-server

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: application.yml 생성
        run: |
          cd src/main/resources 
          echo "${{ secrets.APPLICATION_DEVELOP }}" > ./application.yml
          cat "${{ secrets.APPLICATION_DEVELOP }}"

      - name: 빌드
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        shell: bash

      ######## 여기까지는 CI.yml와 동일 #########

      - name: docker build 가능하도록 환경 설정
        uses: docker/setup-buildx-action@v2.9.1

      - name: docker hub에로그인
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_ACCESSTOKEN }}

      - name: docker image 빌드 및 푸시
        run: |
          docker build --platform linux/amd64 -t moddy1217/moddy-develop -f Dockerfile-Dev .
          docker push moddy1217/moddy-develop

  deploy-cd:
    needs: deploy-ci
    runs-on: ubuntu-22.04

    steps:
      - name: 도커 컨테이너 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVELOP_SERVER_IP }}
          username: ${{ secrets.DEVELOP_SERVER_USER }}
          key: ${{ secrets.DEVELOP_SERVER_KEY }}
          script: |
            cd ~
            ./deploy.sh
