name: MODDY PROD CI

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs:
  build: 
    runs-on: ubuntu-22.04 
    env:
      working-directory: moddy-server

    steps:
    - name: 체크아웃
      uses: actions/checkout@v3

    - name: Set up JDK 17 
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: application.yml 생성
      run: | 
          cd src/main/resources 
          echo "${{ secrets.APPLICATION }}" > ./application.yml

    - name: 빌드
      run: |
          chmod +x gradlew
          ./gradlew build -x test
      shell: bash
